### ISSUE TITLE
Bug: the health/strikes multiplier is applied once per level, not per unit

### ISSUE THREAD

**Issue by ProditorMagnus** [vgaming/less_random#1]
https://forums.wesnoth.org/viewtopic.php?p=688004#p688004

**Comment by vgaming** [comment]
Oof, that was a mistake to label this issue with `status-awaiting-info`. Now there's already https://github.com/vgaming/less_random/issues/2 which I think is the same. I'll close this one as a duplicate to somehow link them together. Sorry for my poor handling of the issue before.
